from typing import Protocol

from sigma_core.planning.domain.aggregates.cycle import Cycle
from sigma_core.planning.domain.value_objects import CycleId
from sigma_core.shared_kernel.value_objects import SpaceId


class CycleRepository(Protocol):
    async def save(self, cycle: Cycle) -> None: ...
    async def get_by_id(self, cycle_id: CycleId) -> Cycle | None: ...
    async def get_active_by_space(self, space_id: SpaceId) -> Cycle | None: ...
    async def list_by_space(self, space_id: SpaceId) -> list[Cycle]: ...
    async def delete(self, cycle_id: CycleId) -> None: ...
