from typing import Protocol
from sigma_core.task_management.domain.entities.area import Area
from sigma_core.shared_kernel.value_objects import AreaId


class AreaRepository(Protocol):
    async def save(self, area: Area) -> None: ...
    async def get_by_id(self, area_id: AreaId) -> Area | None: ...
    async def get_all(self) -> list[Area]: ...
    async def delete(self, area_id: AreaId) -> None: ...