from typing import Protocol
from sigma_core.task_management.domain.aggregates.card import Card
from sigma_core.task_management.domain.card_filter import CardFilter
from sigma_core.task_management.domain.enums import PreWorkflowStage
from sigma_core.shared_kernel.value_objects import CardId, SpaceId, AreaId
from sigma_core.task_management.domain.value_objects import (
    ProjectId,
    EpicId,
    WorkflowStateId,
)


class CardRepository(Protocol):
    async def save(self, card: Card) -> None: ...
    async def get_by_id(self, card_id: CardId) -> Card | None: ...
    async def get_by_space(self, space_id: SpaceId, filter: CardFilter | None = None) -> list[Card]: ...
    async def get_by_pre_workflow_stage(self, space_id: SpaceId, stage: PreWorkflowStage) -> list[Card]: ...
    async def get_by_workflow_state(self, space_id: SpaceId, state_id: WorkflowStateId) -> list[Card]: ...
    async def count_by_workflow_state(self, space_id: SpaceId, state_id: WorkflowStateId, filter: CardFilter | None = None) -> int: ...
    async def get_by_area(self, area_id: AreaId) -> list[Card]: ...
    async def get_by_project(self, project_id: ProjectId) -> list[Card]: ...
    async def get_by_epic(self, epic_id: EpicId) -> list[Card]: ...
    async def delete(self, card_id: CardId) -> None: ...