from typing import Protocol
from sigma_core.task_management.domain.entities.epic import Epic
from sigma_core.task_management.domain.value_objects import EpicId, SpaceId, ProjectId


class EpicRepository(Protocol):
    async def save(self, epic: Epic) -> None: ...
    async def get_by_id(self, epic_id: EpicId) -> Epic | None: ...
    async def get_by_space(self, space_id: SpaceId) -> list[Epic]: ...
    async def get_by_project(self, project_id: ProjectId) -> list[Epic]: ...
    async def delete(self, epic_id: EpicId) -> None: ...