from typing import Protocol
from sigma_core.task_management.domain.entities.project import Project
from sigma_core.task_management.domain.value_objects import ProjectId, AreaId


class ProjectRepository(Protocol):
    async def save(self, project: Project) -> None: ...
    async def get_by_id(self, project_id: ProjectId) -> Project | None: ...
    async def get_by_area(self, area_id: AreaId) -> list[Project]: ...
    async def get_all(self) -> list[Project]: ...
    async def delete(self, project_id: ProjectId) -> None: ...