from typing import Protocol
from sigma_core.task_management.domain.aggregates.space import Space
from sigma_core.task_management.domain.value_objects import SpaceId


class SpaceRepository(Protocol):
    async def save(self, space: Space) -> None: ...
    async def get_by_id(self, space_id: SpaceId) -> Space | None: ...
    async def get_all(self) -> list[Space]: ...
    async def delete(self, space_id: SpaceId) -> None: ...